// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response of the async submit endpoints (HTTP 202).
 */
export type AsyncInferenceLaunchResponse = { task_id: string };
