// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AsyncInferenceApiKind } from "./AsyncInferenceApiKind";
import type { AsyncTaskStatus } from "./AsyncTaskStatus";

/**
 * One row of the `GET /internal/async_tasks` response.
 */
export type AsyncTaskSummary = {
  task_id: string;
  status: AsyncTaskStatus;
  /**
   * Which API shape the task executes (`chat` / `responses` / `messages`),
   * from the stored task params.
   */
  api_kind?: AsyncInferenceApiKind;
  /**
   * Model from the stored request body, exactly as submitted.
   */
  model?: string;
  enqueue_at: string;
  started_at?: string;
  /**
   * Elapsed time for running tasks, total execution time for terminal
   * tasks. `None` while the task has never started.
   */
  duration_ms?: bigint;
  /**
   * Failure message of the latest run, for failed/cancelled tasks.
   */
  error?: string;
  attempts: number;
};
