// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * List status of an async inference task, rolling the durable queue's
 * `pending`/`sleeping` states up into `queued`. Matches the status tags of
 * the public `GET /v1/async_tasks/{task_id}` response.
 */
export type AsyncTaskStatus =
  | "queued"
  | "running"
  | "completed"
  | "failed"
  | "cancelled";
