// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * `GET /v1/async_tasks/{task_id}` response, internally tagged on `status`.
 *
 * Serializes as `{"task_id": ..., "status": "queued", ...}` etc.
 */
export type AsyncTaskStatusResponse =
  | {
      status: "queued";
      task_id: string;
      /**
       * Number of claimable tasks ahead of this one (`None` if unknown).
       */
      queue_position?: bigint;
    }
  | {
      status: "running";
      task_id: string;
      /**
       * RFC 3339 timestamp of when execution first started.
       */
      started_at?: string;
      elapsed_ms?: bigint;
    }
  | {
      status: "completed";
      task_id: string;
      /**
       * The final response, in the same shape as the synchronous API the
       * task was submitted to.
       */
      response: JsonValue;
    }
  | { status: "failed"; task_id: string; error?: JsonValue }
  | { status: "cancelled"; task_id: string; error?: JsonValue };
