// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-(run, rule, table) progress of a cleanup pass.
 */
export type CleanupRunStep = {
  id: string;
  rule_id?: string;
  table_name: string;
  /**
   * `pending` / `running` / `done` / `failed`.
   */
  status: string;
  /**
   * Total rows selected for deletion (phase 1).
   */
  total_rows?: bigint;
  /**
   * Rows actually deleted so far (phase 2, updated after each chunk).
   */
  rows_deleted: bigint;
  started_at: string;
  finished_at?: string;
  error?: string;
};
