// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CleanupRunStep } from "./CleanupRunStep";

/**
 * One cleanup pass with its per-table steps.
 */
export type CleanupRun = {
  id: string;
  /**
   * `schedule` / `manual`.
   */
  trigger: string;
  /**
   * `running` / `completed` / `failed`.
   */
  status: string;
  started_at: string;
  finished_at?: string;
  error?: string;
  steps: Array<CleanupRunStep>;
};
