// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A tag-based cleanup rule, as stored in `tensorzero.cleanup_rules`.
 */
export type CleanupRule = {
  id: string;
  tag_key: string;
  /**
   * When absent, the rule matches every row carrying `tag_key`.
   */
  tag_value?: string;
  older_than_days: number;
  enabled: boolean;
  created_at: string;
  updated_at: string;
};
