// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for `POST /internal/cleanup/rules`.
 */
export type CreateCleanupRuleRequest = {
  tag_key: string;
  tag_value?: string;
  older_than_days: number;
  /**
   * Defaults to `true` when absent.
   */
  enabled?: boolean;
};
