// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for `DELETE /internal/cleanup/rules/{rule_id}`.
 */
export type DeleteCleanupRuleResponse = { deleted: boolean };
