// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpsertVariantPayload } from "./UpsertVariantPayload";

/**
 * Represents a targeted edit operation to apply to a TensorZero config.
 */
export type EditPayload = {
  operation: "upsert_variant";
} & UpsertVariantPayload;
