// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-table storage statistics for an inference-related Postgres table.
 */
export type InferenceTableStorageStats = {
  name: string;
  total_bytes: bigint;
  estimated_rows: bigint;
  partition_count: bigint;
};
