// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InferenceRetentionConfig } from "./InferenceRetentionConfig";
import type { InferenceTableStorageStats } from "./InferenceTableStorageStats";

/**
 * Response for `GET /internal/inference_storage/stats`.
 */
export type InferenceStorageStatsResponse = {
  tables: Array<InferenceTableStorageStats>;
  retention: InferenceRetentionConfig;
};
