// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Protection state of a single inference.
 */
export type InferenceProtectionEntry = {
  id: string;
  function_type: string;
  protected_at: string;
};
