// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Inference retention configuration.
 *
 * `metadata_pinned_by_toml` / `data_pinned_by_toml` indicate that the value
 * is set in `tensorzero.toml` (`[postgres]` section), in which case gateway
 * startup overwrites the database value with the TOML value.
 */
export type InferenceRetentionConfig = {
  metadata_retention_days?: number;
  data_retention_days?: number;
  metadata_pinned_by_toml: boolean;
  data_pinned_by_toml: boolean;
};
