// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for `POST /internal/inferences/{inference_id}/protection`.
 */
export type InferenceProtectionResponse = {
  inference_id: string;
  function_type: string;
  protected_at?: string;
};
