// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CleanupRun } from "./CleanupRun";

/**
 * Response for `GET /internal/cleanup/runs`.
 */
export type ListCleanupRunsResponse = { runs: Array<CleanupRun> };
