// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CleanupRule } from "./CleanupRule";

/**
 * Response for `GET /internal/cleanup/rules`.
 */
export type ListCleanupRulesResponse = { rules: Array<CleanupRule> };
