// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AsyncTaskSummary } from "./AsyncTaskSummary";

/**
 * Response of `GET /internal/async_tasks`.
 */
export type ListAsyncTasksResponse = { tasks: Array<AsyncTaskSummary> };
