// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelAlias } from "./ModelAlias";

/**
 * Lookup table for model aliases, shared across chat/embedding/rerank tables.
 */
export type ModelAliasTable = { aliases: Array<ModelAlias> };
