// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelAliasTarget } from "./ModelAliasTarget";

/**
 * A named alias that maps to one or more (provider, model) targets.
 *
 * `task`: If `Some`, this alias only matches lookups with the same task type
 *   (e.g. "chat", "embedding", "rerank"). If `None`, it matches any task.
 * `targets`: Ordered list of (provider, model) pairs to try.
 */
export type ModelAlias = {
  name: string;
  task?: string;
  targets: Array<ModelAliasTarget>;
  /**
   * Skip a candidate when recent output tok/s is strictly below this value.
   */
  min_tokens_per_sec?: number;
};
