// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for `POST /internal/inferences/{inference_id}/protection`.
 */
export type SetInferenceProtectionRequest = { protected: boolean };
