// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for `POST /internal/cleanup/run`.
 */
export type TriggerCleanupRunResponse = {
  /**
   * Whether `[gateway.cleanup]` is currently enabled. When `false`, no
   * worker is running, so the manual trigger has no effect.
   */
  cleanup_enabled: boolean;
};
