// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * UI-safe alias target: provider + model the alias routes to.
 */
export type UiModelAliasTarget = { provider: string; model: string };
