// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UiModelAliasTarget } from "./UiModelAliasTarget";

/**
 * UI-safe model alias: name plus optional task filter (`chat`, `embedding`, `rerank`).
 */
export type UiModelAlias = {
  name: string;
  task?: string;
  targets?: Array<UiModelAliasTarget>;
};
