// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for `PUT /internal/cleanup/rules/{rule_id}`.
 * Full-replace semantics: every field overwrites the stored rule
 * (`tag_value: null` clears the value filter).
 */
export type UpdateCleanupRuleRequest = {
  tag_key: string;
  tag_value?: string;
  older_than_days: number;
  enabled: boolean;
};
