// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for `POST /internal/inference_storage/retention`.
 * A `null` (or absent) value means "keep forever" and deletes the key.
 */
export type UpdateInferenceRetentionRequest = {
  metadata_retention_days?: number;
  data_retention_days?: number;
};
